gbl: Fix cross-device renaming in rewrite_rust_project_path.py
Trying to os.rename() some temporary file created in /tmp to
rust-project.json file inside of the project working dir may lead to an
error if the project resides on a different file system, with an error
like this:

    Traceback (most recent call last):
        os.rename(fp.name, rust_project_json_path)
        OSError: [Errno 18] Invalid cross-device link:
        '/tmp/tmphk2r7xjg' -> '.../rust-project.json'

Use shutil.move() instead, which is able to move files across different
file systems.

Change-Id: I1c16cfea1b475a6c341306577885be74226cd206
Signed-off-by: Sam Protsenko <semen.protsenko@linaro.org>